version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/filmweb
      - SPRING_DATASOURCE_USERNAME=filmweb
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5452:5432"
    container_name: db
    environment:
      - POSTGRES_USER=filmweb
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=filmweb
