version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    container_name: filmweb-backend
    depends_on:
      - database
      - redis-cache
    env_file:
      - ../env/backend.env
  database:
    image: 'postgres:13.1-alpine'
    ports:
      - "5452:5432"
    container_name: filmweb-database
    volumes:
      - filmweb_data:/var/lib/postgresql/data
      - ../src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../env/postgres.env
  redis-cache:
    image: "redis"
    ports:
      - "6379:6379"
    container_name: filmweb-redis-cache
volumes:
  filmweb_data:
